import { Platform, StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#0f172a' },
  container: { flex: 1, backgroundColor: '#0b1220' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0b1220' },
  header: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 14,
    backgroundColor: '#0f172a',
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: { fontSize: 20, fontWeight: '800', color: 'white' },
  headerActions: { flexDirection: 'row', gap: 8, marginLeft: 'auto', alignItems: 'center' },
  tabBtn: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 999, backgroundColor: '#020617' },
  tabBtnActive: { backgroundColor: '#e5e7eb' },
  tabText: { fontSize: 12, fontWeight: '600', color: '#e5e7eb' },
  tabTextActive: { color: 'white' },
  logoutBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#1f2937',
    backgroundColor: '#020617',
  },
  logoutText: { fontSize: 12, fontWeight: '600', color: '#e5e7eb' },
  card: {
    marginHorizontal: 16,
    marginVertical: 10,
    padding: 18,
    borderRadius: 24,
    backgroundColor: '#020617',
    borderWidth: 1,
    borderColor: '#1e293b',
    gap: 10,
  },
  h1: { fontSize: 22, fontWeight: '800', color: '#e5e7eb' },
  muted: { color: '#64748b' },
  label: { marginTop: 8, fontSize: 12, fontWeight: '700', color: '#334155' },
  input: {
    borderWidth: 1,
    borderColor: '#1f2937',
    backgroundColor: '#020617',
    color: '#e5e7eb',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  error: { color: '#b91c1c', marginTop: 6 },
  primaryBtn: {
    marginTop: 8,
    backgroundColor: '#f97316',
    borderRadius: 999,
    paddingVertical: 12,
    alignItems: 'center',
  },
  primaryBtnText: { color: 'white', fontWeight: '800' },
  btnDisabled: { opacity: 0.6 },
  eventCard: {
    padding: 14,
    borderRadius: 24,
    backgroundColor: '#020617',
    borderWidth: 1,
    borderColor: '#1e293b',
    gap: 8,
  },
  eventImage: { width: '100%', height: 150, borderRadius: 20, marginBottom: 8 },
  detailImage: { width: '100%', height: 220, borderRadius: 24, marginBottom: 12 },
  eventTitle: { fontSize: 18, fontWeight: '800', color: '#e5e7eb' },
  eventMeta: { marginTop: 4, fontSize: 13, fontWeight: '700', color: '#f97316' },
  link: { color: '#2563eb', fontWeight: '700' },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  modalCard: { width: '100%', maxWidth: 420, padding: 18, borderRadius: 24, backgroundColor: '#020617' },
  code: {
    marginTop: 10,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', web: 'monospace' }),
    fontSize: 12,
    color: '#e5e7eb',
  },
  codeSmall: {
    marginTop: 8,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', web: 'monospace' }),
    fontSize: 11,
    color: '#0f172a',
  },
})

